[config]
default_to_workspace = false

[env]
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passw0rd"
DATABASE_NAME = "app"

[tasks.run]
command = "cargo"
args = ["run", "${@}"]

[tasks.docker_run]
command = "docker-compose"
args = ["up", "-d", "--build"]

[tasks.docker_log]
command = "docker-compose"
args = ["logs", "${@}"]

[tasks.docker_stop]
command = "docker-compose"
args = ["down", "${@}"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.watch]
run_task = { name = ["fmt"] }
watch = true

